import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, HTTPException, Request, status
from sqlalchemy import func, insert, select
from sqlalchemy.orm import Session

from app.core.requests import read_limited_body
from app.db.tables import AuditEvent, Customer, LeakFinding, PaymentEvent, RecoveryCase
from app.domain.enums import CaseState, PaymentEventType
from app.domain.models import NormalizedPaymentEvent
from app.ingestion.csv_loader import import_csv
from app.leak_analysis import detect_and_store_leaks, finding_sort_key
from simulator.generator import DEFAULT_SEED, HISTORICAL_PAYMENT_COUNT, generate_csv

router = APIRouter(prefix="/api/v1/data", tags=["data"])


def _demo_event_query():
    return select(PaymentEvent).where(
        PaymentEvent.provider == "csv_import",
        PaymentEvent.event_id.like("demo_%"),
    )


def _demo_counts(session: Session) -> tuple[int, int, int]:
    demo_filter = (
        PaymentEvent.provider == "csv_import",
        PaymentEvent.event_id.like("demo_%"),
    )
    total = session.scalar(
        select(func.count()).select_from(PaymentEvent).where(*demo_filter)
    ) or 0
    failures = session.scalar(
        select(func.count())
        .select_from(PaymentEvent)
        .where(*demo_filter, PaymentEvent.status == "failed")
    ) or 0
    successes = session.scalar(
        select(func.count())
        .select_from(PaymentEvent)
        .where(*demo_filter, PaymentEvent.status == "captured")
    ) or 0
    return total, successes, failures


def _bulk_import_demo_history(session: Session, content: str) -> int:
    """Insert the trusted deterministic demo corpus with one batched transaction.

    The normal CSV importer intentionally performs per-event state-machine work.
    That is correct for arbitrary ingestion, but it produces thousands of remote
    round trips against Supabase and can exceed a Vercel Function request budget.
    The 999-row demo corpus is generated by this repository and every row is an
    independent payment attempt, so we can construct the exact equivalent rows
    in batches and keep the interactive demo responsive.
    """
    customer_rows: list[dict[str, object]] = []
    payment_rows: list[dict[str, object]] = []
    case_rows: list[dict[str, object]] = []
    audit_rows: list[dict[str, object]] = []
    seen_customers: set[str] = set()

    for row in csv.DictReader(StringIO(content)):
        obligation_raw = (
            row.get("obligation_reference")
            or row.get("order_id")
            or row.get("obligation")
            or ""
        )
        obligation_reference = obligation_raw.strip() or None
        event = NormalizedPaymentEvent.model_validate(
            {
                "event_id": row["event_id"],
                "provider_event_id": row["event_id"],
                "event_type": row["event_type"],
                "payment_id": row["payment_id"],
                "obligation_reference": obligation_reference,
                "customer_id": row["customer_id"] or None,
                "amount": row["amount"],
                "currency": row["currency"],
                "method": row["method"] or None,
                "status": row["status"],
                "error_source": row.get("error_source") or None,
                "error_step": row.get("error_step") or None,
                "error_code": row["error_code"] or None,
                "error_reason": row["error_reason"] or None,
                "occurred_at": row["occurred_at"],
                "provider": "csv_import",
                "raw_hash": hashlib.sha256(str(sorted(row.items())).encode()).hexdigest(),
                "raw_body": None,
            }
        )

        payment_rows.append(event.model_dump())

        if event.customer_id and event.customer_id not in seen_customers:
            seen_customers.add(event.customer_id)
            customer_rows.append(
                {
                    "customer_id": event.customer_id,
                    "tenure_days": int(row.get("tenure_days") or 0),
                    "successful_payments": int(row.get("successful_payments") or 0),
                    "prior_failures": int(row.get("prior_failures") or 0),
                    "preferred_method": row.get("preferred_method") or None,
                    "consent": (row.get("consent") or "").lower() in {"true", "1", "yes"},
                    "locale": row.get("locale") or None,
                }
            )

        if event.event_type == PaymentEventType.FAILED:
            case_id = f"case_{event.obligation_reference or event.payment_id}"
            case_rows.append(
                {
                    "case_id": case_id,
                    "customer_id": event.customer_id,
                    "payment_id": event.payment_id,
                    "obligation_reference": event.obligation_reference,
                    "amount_at_risk": event.amount,
                    "state": CaseState.DETECTED,
                    "attempts": 0,
                }
            )
            detected_payload: dict[str, object] = {"payment_id": event.payment_id}
            if event.obligation_reference is not None:
                detected_payload["obligation_reference"] = event.obligation_reference
            audit_rows.extend(
                [
                    {
                        "case_id": case_id,
                        "event_type": "case.detected",
                        "payload": detected_payload,
                    },
                    {
                        "case_id": case_id,
                        "event_type": "event.recorded",
                        "payload": {
                            "event_id": event.event_id,
                            "event_type": event.event_type,
                        },
                    },
                ]
            )

    if len(payment_rows) != HISTORICAL_PAYMENT_COUNT:
        raise ValueError("demo generator did not produce exactly 999 payments")

    session.execute(insert(Customer), customer_rows)
    session.execute(insert(PaymentEvent), payment_rows)
    session.execute(insert(RecoveryCase), case_rows)
    session.execute(insert(AuditEvent), audit_rows)
    return len(payment_rows)


def _simulation_payload(
    session: Session,
    *,
    payments_created: int,
    duplicates: int,
) -> dict[str, object]:
    total, successes, failures = _demo_counts(session)
    findings = session.scalars(select(LeakFinding)).all()
    findings.sort(key=finding_sort_key)
    return {
        "payments_created": payments_created,
        "payments_total": total,
        "successes": successes,
        "failures": failures,
        "duplicates": duplicates,
        "findings": len(findings),
        "top_finding_id": findings[0].finding_id if findings else None,
        "seed": DEFAULT_SEED,
        "already_present": payments_created == 0,
    }


@router.post("/import", status_code=status.HTTP_201_CREATED)
async def import_data(request: Request) -> dict[str, int]:
    try:
        content = (await read_limited_body(request)).decode("utf-8")
    except UnicodeDecodeError as error:
        raise HTTPException(status_code=422, detail="CSV must be UTF-8") from error

    with request.app.state.session_factory() as session:
        try:
            imported, duplicates = import_csv(session, content)
        except ValueError as error:
            session.rollback()
            raise HTTPException(status_code=422, detail=str(error)) from error
        session.commit()
    return {"imported": imported, "duplicates": duplicates}


@router.post("/simulate-999", status_code=status.HTTP_201_CREATED)
def simulate_999_payments(request: Request) -> dict[str, object]:
    """Create or reuse the deterministic Issue #47 merchant history.

    The generated corpus is inserted in batches so the hosted Supabase path is
    fast enough for an interactive Vercel request. Repeated clicks are safe: if
    the exact 999-row demo corpus is already present, the endpoint returns the
    persisted result instead of failing with 409.
    """
    csv_content = generate_csv(
        seed=DEFAULT_SEED,
        event_count=HISTORICAL_PAYMENT_COUNT,
    )

    with request.app.state.session_factory() as session:
        existing_payments = session.scalar(select(func.count()).select_from(PaymentEvent)) or 0
        existing_demo_payments, _, _ = _demo_counts(session)

        if existing_demo_payments == HISTORICAL_PAYMENT_COUNT:
            findings = session.scalars(select(LeakFinding)).all()
            if not findings:
                detect_and_store_leaks(session)
                session.commit()
            return _simulation_payload(
                session,
                payments_created=0,
                duplicates=HISTORICAL_PAYMENT_COUNT,
            )

        if existing_payments:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=(
                    "demo payment history requires either an empty database "
                    "or the existing 999-row demo corpus"
                ),
            )

        try:
            imported = _bulk_import_demo_history(session, csv_content)
            findings = detect_and_store_leaks(session)
            if imported != HISTORICAL_PAYMENT_COUNT or len(findings) != 37:
                raise ValueError("demo payment history could not be created cleanly")
            session.commit()
        except Exception:
            session.rollback()
            raise

        return _simulation_payload(
            session,
            payments_created=imported,
            duplicates=0,
        )
